version: '3'
services:
  express:
    build: ./cash-register-express
    command: npm start
    ports:
      - '3000:3000'
    links:
      - mongo
    restart: unless-stopped
  mongo:
      image: mongo
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
        MONGO_DATA_DIR: /data/db
        MONGO_LOG_DIR: /dev/null
      volumes:
        - mongo-volume:/data/db
      ports:
        - 27017:27017
      restart: unless-stopped
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    restart: unless-stopped

volumes:
  mongo-volume:
